name: Test an officially supported backend
inputs:
  backend:
    required: true
    description: Backend type to test
runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-dictum
    - uses: actions/checkout@v3
      with:
        repository: discover-labs/dictum-backend-${{ inputs.backend }}
        path: ${{ inputs.backend }}

    - name: Find latest compatible version
      id: version
      run: ls -l # echo "::set-output name=tag::$(git --git-dir ../${{ inputs.backend }} tag | poetry run python -m dictum_core.utils.version)"
      working-directory: dictum-core
      shell: bash

    - name: Checkout to tag
      run: git checkout ${{ steps.version.outputs.tag }}
      working-directory: ${{ inputs.backend }}
      shell: bash

    - run: poetry build
      working-directory: ${{ inputs.backend }}
      shell: bash

    - run: poetry run pip install ../${{ inputs.backend }}/dist/*.whl
      working-directory: dictum-core
      shell: bash

    - run: poetry run pytest ../${{ inputs.backend }}/tests/
      working-directory: dictum-core
      shell: bash
