name: Test an officially supported backend
inputs:
  backend:
    required: true
    description: Backend type to test
runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-dictum

    - run: echo "::set-output name=prefix::$(poetry run python -m dictum_core.utils.prefix)"
      id: prefix
      shell: bash
      working-directory: dictum-core

    - uses: oprypin/find-latest-tag@v1
      id: find_tag
      with:
        repository: discover-labs/dictum-backend-${{ inputs.backend }}
        prefix: ${{ steps.prefix.outputs.prefix }}

    - uses: actions/checkout@v3
      with:
        repository: discover-labs/dictum-backend-${{ inputs.backend }}
        path: ${{ inputs.backend }}
        ref: ${{ steps.find_tag.outputs.tag }}

    - run: poetry build
      working-directory: ${{ inputs.backend }}
      shell: bash

    - run: poetry run pip install ../${{ inputs.backend }}/dist/*.whl
      working-directory: dictum-core
      shell: bash

    - run: poetry run pytest ../${{ inputs.backend }}/tests/
      working-directory: dictum-core
      shell: bash
