name: Publish package to PyPi

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    defaults:
      run:
        working-directory: dictum-core
    env:
      POETRY_PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-dictum
        with:
          python-version: 3.9
      - run: poetry publish --build
