name: Run Tests

on:
  push:
    paths:
      - dictum-core/**
      - .github/**
  workflow_dispatch:

jobs:
  test:
    name: Run dictum-core tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dictum-core
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-dictum
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry run pytest --durations=5
      - uses: codecov/codecov-action@v3
        with:
          files: dictum-core/coverage.xml

  test-backend-postgres:
    name: Run tests for Postgres backend
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-backend
        with:
          backend: postgres

  # test-backend-mariadb:
  #   name: Run tests for MariaDB backend
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/test-backend
  #       with:
  #         backend: mariadb
